# Generated by Django 5.1.1 on 2024-09-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpet', '0002_contactus_uploded_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='Uploded_time',
            field=models.DateTimeField(null=True),
        ),
    ]
